from dataclasses import dataclass

@dataclass
class model_config:
    ...

@dataclass
class train_config:
    ...

@dataclass
class data_config:
    num_workers : int = ...
    pin_memory : bool = ...
    persistent_workers : bool = ...
    prefetch_factor : int = ...
    in_order : bool = ...